# development:
#   adapter: postgresql
#   database: lembra_development
#   pool: 5
#   timeout: 5000
#
# test:
#   adapter: postgresql
#   database: lembra_test
#   pool: 5
#   timeout: 5000
#
# production:
#   adapter: postgresql
#   database: lembra_production
#   pool: 5
#   timeout: 5000
development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3
